export const BEGIN_TEST_LINE = "Delete this line to begin the test!";

export const EXTRA_WORDS = [
	"aar",
	"bar",
	"car",
	"dar",
	"ear",
	"far",
	"gar",
	"har",
	"iar",
	"jar",
	"kar",
	"lar",
	"mar",
	"nar",
	"oar",
	"par",
	"qar",
	"rar",
	"sar",
	"tar",
	"uar",
	"var",
	"war",
	"xar",
	"yar",
	"zar"
];
export const EXTRA_SENTENCES = [
	"The greatest glory in living lies not in never falling, but in rising every time we fall.",
	"The way to get started is to quit talking and begin doing.",
	"Your time is limited, so don't waste it living someone else's life.",
	"If life were predictable it would cease to be life, and be without flavor.",
	"If you look at what you have in life, you'll always have more.",
	"If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
	"Life is what happens when you're busy making other plans.",
	"Spread love everywhere you go. Let no one ever come to you without leaving happier.",
	"When you reach the end of your rope, tie a knot in it and hang on.",
	"Always remember that you are absolutely unique. Just like everyone else.",
	"Don't judge each day by the harvest you reap but by the seeds that you plant.",
	"The future belongs to those who believe in the beauty of their dreams.",
	"Tell me and I forget. Teach me and I remember. Involve me and I learn.",
	"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
	"It is during our darkest moments that we must focus to see the light.",
	"Whoever is happy will make others happy too.",
	"Do not go where the path may lead, go instead where there is no path and leave a trail.",
	"You will face many defeats in life, but never let yourself be defeated.",
	"The greatest glory in living lies not in never falling, but in rising every time we fall.",
	"In the end, it's not the years in your life that count. It's the life in your years.",
	"Never let the fear of striking out keep you from playing the game.",
	"Life is either a daring adventure or nothing at all.",
	"Many of life's failures are people who did not realize how close they were to success when they gave up.",
	"You have within you right now, everything you need to deal with whatever the world can throw at you.",
	"Believe you can and you're halfway there.",
	"What we achieve inwardly will change outer reality.",
	"Change your thoughts and you change your world.",
	"The only limit to our realization of tomorrow will be our doubts of today.",
	"The purpose of our lives is to be happy.",
	"Life is what happens when you're busy making other plans.",
	"Get busy living or get busy dying.",
	"You only live once, but if you do it right, once is enough.",
	"Many of life's failures are people who did not realize how close they were to success when they gave up.",
	"If you want to live a happy life, tie it to a goal, not to people or things.",
	"Never let the fear of striking out keep you from playing the game.",
	"Money and success don’t change people; they merely amplify what is already there.",
	"Your time is limited, so don’t waste it living someone else’s life.",
	"Not how long, but how well you have lived is the main thing.",
	"If life were predictable it would cease to be life and be without flavor.",
	"The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.",
	"In order to write about life first you must live it.",
	"The big lesson in life, baby, is never be scared of anyone or anything.",
	"Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth.",
	"Curiosity about life in all of its aspects, I think, is still the secret of great creative people.",
	"Life is not a problem to be solved, but a reality to be experienced.",
	"The unexamined life is not worth living.",
	"Turn your wounds into wisdom.",
	"The way I see it, if you want the rainbow, you gotta put up with the rain.",
	"Do all the good you can, for all the people you can, in all the ways you can, as long as you can."
];

export const EXTRA_DELETE_SENTENCES = [
	"DELETE ME",
	"Can you get to me?",
	"You are not good enough",
	"Stop trying so hard",
	"Give up",
	"Get out of here",
	"You don't use vim btw",
	"You are too weak for me",
	"Too slow",
	"You will never win"
];

export const EXTRA_SYMBOLS = ["#", "*", "+", "%", "@", "$", "-"];
